package dev.jodat.osqueryspringboot.config;

import dev.jodat.osqueryspringboot.enums.OS;
import org.springframework.context.annotation.Configuration;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Configuration
public class OsQuerySchema {

    private static final Map<String, List<OS>> TABLES = new HashMap<>(277);
    
    public static List<String> WINDOWS = new ArrayList<>();
    public static List<String> LINUX = new ArrayList<>();
    public static List<String> MAC = new ArrayList<>();
    public static String[] START_COMMAND = {"osqueryi", "--json"};
    
    static {
        List<OS> windows = List.of(OS.WINDOWS);
        List<OS> linux = List.of(OS.LINUX);
        List<OS> mac = List.of(OS.MAC);
        List<OS> macAndLinux = List.of(OS.MAC, OS.LINUX);
        List<OS> windowsAndLinux = List.of(OS.WINDOWS, OS.LINUX);
        List<OS> macAndLinuxAndWindows = List.of(OS.MAC, OS.LINUX, OS.WINDOWS);

        TABLES.put("account_policy_data", mac);
        TABLES.put("acpi_tables", macAndLinux);
        TABLES.put("ad_config", mac);
        TABLES.put("alf", mac);
        TABLES.put("alf_exceptions", mac);
        TABLES.put("alf_explicit_auths", mac);
        TABLES.put("app_schemes", mac);
        TABLES.put("apparmor_events", linux);
        TABLES.put("apparmor_profiles", linux);
        TABLES.put("appcompat_shims", windows);
        TABLES.put("apps", mac);
        TABLES.put("apt_sources", linux);
        TABLES.put("arp_cache", macAndLinuxAndWindows);
        TABLES.put("asl", mac);
        TABLES.put("atom_packages", macAndLinuxAndWindows);
        TABLES.put("augeas", macAndLinux);
        TABLES.put("authenticode", windows);
        TABLES.put("authorization_mechanisms", mac);
        TABLES.put("authorizations", mac);
        TABLES.put("authorized_keys", macAndLinux);
        TABLES.put("autoexec", windows);
        TABLES.put("azure_instance_metadata", macAndLinuxAndWindows);
        TABLES.put("azure_instance_tags", macAndLinuxAndWindows);
        TABLES.put("background_activities_moderator", windows);
        TABLES.put("battery", mac);
        TABLES.put("bitlocker_info", windows);
        TABLES.put("block_devices", macAndLinux);
        TABLES.put("bpf_process_events", linux);
        TABLES.put("bpf_socket_events", linux);
        TABLES.put("browser_plugins", mac);
        TABLES.put("carbon_black_info", macAndLinuxAndWindows);
        TABLES.put("carves", macAndLinuxAndWindows);
        TABLES.put("certificates", macAndLinuxAndWindows);
        TABLES.put("chassis_info", windows);
        TABLES.put("chocolatey_packages", windows);
        TABLES.put("chrome_extension_content_scripts", macAndLinuxAndWindows);
        TABLES.put("chrome_extensions", macAndLinuxAndWindows);
        TABLES.put("connected_displays", mac);
        TABLES.put("connectivity", windows);
        TABLES.put("cpu_info", macAndLinuxAndWindows);
        TABLES.put("cpu_time", macAndLinux);
        TABLES.put("cpuid", macAndLinuxAndWindows);
        TABLES.put("crashes", mac);
        TABLES.put("crontab", macAndLinux);
        TABLES.put("cups_destinations", mac);
        TABLES.put("cups_jobs", mac);
        TABLES.put("curl", macAndLinuxAndWindows);
        TABLES.put("curl_certificate", macAndLinuxAndWindows);
        TABLES.put("deb_packages", linux);
        TABLES.put("default_environment", windows);
        TABLES.put("device_file", macAndLinux);
        TABLES.put("device_firmware", mac);
        TABLES.put("device_hash", macAndLinux);
        TABLES.put("device_partitions", macAndLinux);
        TABLES.put("disk_encryption", macAndLinux);
        TABLES.put("disk_events", mac);
        TABLES.put("disk_info", windows);
        TABLES.put("dns_cache", windows);
        TABLES.put("dns_resolvers", macAndLinux);
        TABLES.put("docker_container_envs", macAndLinux);
        TABLES.put("docker_container_fs_changes", macAndLinux);
        TABLES.put("docker_container_labels", macAndLinux);
        TABLES.put("docker_container_mounts", macAndLinux);
        TABLES.put("docker_container_networks", macAndLinux);
        TABLES.put("docker_container_ports", macAndLinux);
        TABLES.put("docker_container_processes", macAndLinux);
        TABLES.put("docker_container_stats", macAndLinux);
        TABLES.put("docker_containers", macAndLinux);
        TABLES.put("docker_image_history", macAndLinux);
        TABLES.put("docker_image_labels", macAndLinux);
        TABLES.put("docker_image_layers", macAndLinux);
        TABLES.put("docker_images", macAndLinux);
        TABLES.put("docker_info", macAndLinux);
        TABLES.put("docker_network_labels", macAndLinux);
        TABLES.put("docker_networks", macAndLinux);
        TABLES.put("docker_version", macAndLinux);
        TABLES.put("docker_volume_labels", macAndLinux);
        TABLES.put("docker_volumes", macAndLinux);
        TABLES.put("drivers", windows);
        TABLES.put("ec2_instance_metadata", macAndLinuxAndWindows);
        TABLES.put("ec2_instance_tags", macAndLinuxAndWindows);
        TABLES.put("es_process_events", mac);
        TABLES.put("es_process_file_events", mac);
        TABLES.put("etc_hosts", macAndLinuxAndWindows);
        TABLES.put("etc_protocols", macAndLinuxAndWindows);
        TABLES.put("etc_services", macAndLinuxAndWindows);
        TABLES.put("event_taps", mac);
        TABLES.put("extended_attributes", macAndLinux);
        TABLES.put("fan_speed_sensors", mac);
        TABLES.put("file", macAndLinuxAndWindows);
        TABLES.put("file_events", macAndLinux);
        TABLES.put("firefox_addons", macAndLinuxAndWindows);
        TABLES.put("gatekeeper", mac);
        TABLES.put("gatekeeper_approved_apps", mac);
        TABLES.put("groups", macAndLinuxAndWindows);
        TABLES.put("hardware_events", macAndLinux);
        TABLES.put("hash", macAndLinuxAndWindows);
        TABLES.put("homebrew_packages", mac);
        TABLES.put("hvci_status", windows);
        TABLES.put("ibridge_info", mac);
        TABLES.put("ie_extensions", windows);
        TABLES.put("intel_me_info", windowsAndLinux);
        TABLES.put("interface_addresses", macAndLinuxAndWindows);
        TABLES.put("interface_details", macAndLinuxAndWindows);
        TABLES.put("interface_ipv6", macAndLinux);
        TABLES.put("iokit_devicetree", mac);
        TABLES.put("iokit_registry", mac);
        TABLES.put("iptables", linux);
        TABLES.put("kernel_extensions", mac);
        TABLES.put("kernel_info", macAndLinuxAndWindows);
        TABLES.put("kernel_keys", linux);
        TABLES.put("kernel_modules", linux);
        TABLES.put("kernel_panics", mac);
        TABLES.put("keychain_acls", mac);
        TABLES.put("keychain_items", mac);
        TABLES.put("known_hosts", macAndLinux);
        TABLES.put("kva_speculative_info", windows);
        TABLES.put("last", macAndLinux);
        TABLES.put("launchd", mac);
        TABLES.put("launchd_overrides", mac);
        TABLES.put("listening_ports", macAndLinuxAndWindows);
        TABLES.put("load_average", macAndLinux);
        TABLES.put("location_services", mac);
        TABLES.put("logged_in_users", macAndLinuxAndWindows);
        TABLES.put("logical_drives", windows);
        TABLES.put("logon_sessions", windows);
        TABLES.put("lxd_certificates", linux);
        TABLES.put("lxd_cluster", linux);
        TABLES.put("lxd_cluster_members", linux);
        TABLES.put("lxd_images", linux);
        TABLES.put("lxd_instance_config", linux);
        TABLES.put("lxd_instance_devices", linux);
        TABLES.put("lxd_instances", linux);
        TABLES.put("lxd_networks", linux);
        TABLES.put("lxd_storage_pools", linux);
        TABLES.put("magic", macAndLinux);
        TABLES.put("managed_policies", mac);
        TABLES.put("md_devices", linux);
        TABLES.put("md_drives", linux);
        TABLES.put("md_personalities", linux);
        TABLES.put("mdfind", mac);
        TABLES.put("mdls", mac);
        TABLES.put("memory_array_mapped_addresses", macAndLinux);
        TABLES.put("memory_arrays", macAndLinux);
        TABLES.put("memory_device_mapped_addresses", macAndLinux);
        TABLES.put("memory_devices", macAndLinuxAndWindows);
        TABLES.put("memory_error_info", macAndLinux);
        TABLES.put("memory_info", linux);
        TABLES.put("memory_map", linux);
        TABLES.put("mounts", macAndLinux);
        TABLES.put("msr", linux);
        TABLES.put("nfs_shares", mac);
        TABLES.put("npm_packages", macAndLinuxAndWindows);
        TABLES.put("ntdomains", windows);
        TABLES.put("ntfs_acl_permissions", windows);
        TABLES.put("ntfs_journal_events", windows);
        TABLES.put("nvram", mac);
        TABLES.put("oem_strings", macAndLinux);
        TABLES.put("office_mru", windows);
        TABLES.put("os_version", macAndLinuxAndWindows);
        TABLES.put("osquery_events", macAndLinuxAndWindows);
        TABLES.put("osquery_extensions", macAndLinuxAndWindows);
        TABLES.put("osquery_flags", macAndLinuxAndWindows);
        TABLES.put("osquery_info", macAndLinuxAndWindows);
        TABLES.put("osquery_packs", macAndLinuxAndWindows);
        TABLES.put("osquery_registry", macAndLinuxAndWindows);
        TABLES.put("osquery_schedule", macAndLinuxAndWindows);
        TABLES.put("package_bom", mac);
        TABLES.put("package_install_history", mac);
        TABLES.put("package_receipts", mac);
        TABLES.put("password_policy", mac);
        TABLES.put("patches", windows);
        TABLES.put("pci_devices", macAndLinux);
        TABLES.put("physical_disk_performance", windows);
        TABLES.put("pipes", windows);
        TABLES.put("platform_info", macAndLinuxAndWindows);
        TABLES.put("plist", mac);
        TABLES.put("portage_keywords", linux);
        TABLES.put("portage_packages", linux);
        TABLES.put("portage_use", linux);
        TABLES.put("power_sensors", mac);
        TABLES.put("powershell_events", windows);
        TABLES.put("preferences", mac);
        TABLES.put("prefetch", windows);
        TABLES.put("process_envs", macAndLinux);
        TABLES.put("process_etw_events", windows);
        TABLES.put("process_events", macAndLinux);
        TABLES.put("process_file_events", linux);
        TABLES.put("process_memory_map", macAndLinuxAndWindows);
        TABLES.put("process_namespaces", linux);
        TABLES.put("process_open_files", macAndLinux);
        TABLES.put("process_open_pipes", mac);
        TABLES.put("process_open_sockets", macAndLinuxAndWindows);
        TABLES.put("processes", macAndLinuxAndWindows);
        TABLES.put("programs", windows);
        TABLES.put("prometheus_metrics", macAndLinux);
        TABLES.put("python_packages", macAndLinuxAndWindows);
        TABLES.put("quicklook_cache", mac);
        TABLES.put("registry", windows);
        TABLES.put("routes", macAndLinuxAndWindows);
        TABLES.put("rpm_package_files", linux);
        TABLES.put("rpm_packages", linux);
        TABLES.put("running_apps", mac);
        TABLES.put("safari_extensions", mac);
        TABLES.put("sandboxes", mac);
        TABLES.put("scheduled_tasks", windows);
        TABLES.put("screenlock", mac);
        TABLES.put("seccomp_events", linux);
        TABLES.put("secureboot", macAndLinuxAndWindows);
        TABLES.put("security_profile_info", windows);
        TABLES.put("selinux_events", linux);
        TABLES.put("selinux_settings", linux);
        TABLES.put("services", windows);
        TABLES.put("shadow", linux);
        TABLES.put("shared_folders", mac);
        TABLES.put("shared_memory", linux);
        TABLES.put("shared_resources", windows);
        TABLES.put("sharing_preferences", mac);
        TABLES.put("shell_history", macAndLinux);
        TABLES.put("shellbags", windows);
        TABLES.put("shimcache", windows);
        TABLES.put("signature", mac);
        TABLES.put("sip_config", mac);
        TABLES.put("smbios_tables", macAndLinux);
        TABLES.put("smc_keys", mac);
        TABLES.put("socket_events", macAndLinux);
        TABLES.put("ssh_configs", macAndLinuxAndWindows);
        TABLES.put("startup_items", macAndLinuxAndWindows);
        TABLES.put("sudoers", macAndLinux);
        TABLES.put("suid_bin", macAndLinux);
        TABLES.put("syslog_events", linux);
        TABLES.put("system_controls", macAndLinux);
        TABLES.put("system_extensions", mac);
        TABLES.put("system_info", macAndLinuxAndWindows);
        TABLES.put("systemd_units", linux);
        TABLES.put("temperature_sensors", mac);
        TABLES.put("time", macAndLinuxAndWindows);
        TABLES.put("time_machine_backups", mac);
        TABLES.put("time_machine_destinations", mac);
        TABLES.put("tpm_info", windows);
        TABLES.put("ulimit_info", macAndLinux);
        TABLES.put("unified_log", mac);
        TABLES.put("uptime", macAndLinuxAndWindows);
        TABLES.put("usb_devices", macAndLinux);
        TABLES.put("user_events", macAndLinux);
        TABLES.put("user_groups", macAndLinuxAndWindows);
        TABLES.put("user_interaction_events", mac);
        TABLES.put("user_ssh_keys", macAndLinuxAndWindows);
        TABLES.put("userassist", windows);
        TABLES.put("users", macAndLinuxAndWindows);
        TABLES.put("video_info", windows);
        TABLES.put("virtual_memory_info", mac);
        TABLES.put("wifi_networks", mac);
        TABLES.put("wifi_status", mac);
        TABLES.put("wifi_survey", mac);
        TABLES.put("winbaseobj", windows);
        TABLES.put("windows_crashes", windows);
        TABLES.put("windows_eventlog", windows);
        TABLES.put("windows_events", windows);
        TABLES.put("windows_firewall_rules", windows);
        TABLES.put("windows_optional_features", windows);
        TABLES.put("windows_search", windows);
        TABLES.put("windows_security_center", windows);
        TABLES.put("windows_security_products", windows);
        TABLES.put("windows_update_history", windows);
        TABLES.put("wmi_bios_info", windows);
        TABLES.put("wmi_cli_event_consumers", windows);
        TABLES.put("wmi_event_filters", windows);
        TABLES.put("wmi_filter_consumer_binding", windows);
        TABLES.put("wmi_script_event_consumers", windows);
        TABLES.put("xprotect_entries", mac);
        TABLES.put("xprotect_meta", mac);
        TABLES.put("xprotect_reports", mac);
        TABLES.put("yara", macAndLinuxAndWindows);
        TABLES.put("yara_events", macAndLinuxAndWindows);
        TABLES.put("ycloud_instance_metadata", macAndLinuxAndWindows);
        TABLES.put("yum_sources", linux);

        TABLES.forEach((e , t ) -> {
            if (t.contains(OS.LINUX)) {
                LINUX.add(e);
            }
            if (t.contains(OS.MAC)) {
                MAC.add(e);
            }
            if (t.contains(OS.WINDOWS)) {
                WINDOWS.add(e);
            }
        });

    }

}
